export const exportOwnUserIdTables = [
  "profile_private",
  "user_settings",
  "user_presence",
  "user_library",
  "user_game_stats",
  "game_sessions",
  "user_achievements",
  "achievement_progress",
  "user_wishlist",
  "user_reviews",
  "user_devices",
  "user_notifications",
  "user_activity",
  "user_badges",
  "user_social_links",
  "user_hardware",
  "user_game_collections",
  "user_game_collection_items",
  "user_profile_cosmetics",
  "user_cloud_save_sets",
  "user_cloud_save_files",
  "profile_showcases",
  "screenshots",
  "screenshot_likes",
  "price_alerts",
  "account_deletion_requests",
  "developer_applications",
  "overlay_settings",
  "performance_snapshots",
  "mod_profiles",
  "mods",
  "mod_reviews",
  "user_mod_installs",
  "user_mod_profile_entries",
  "user_mod_install_files",
  "platform_accounts",
  "friend_merge_suggestions",
  "activity_feed",
  "controller_layouts",
  "chat_room_members",
  "store_reviews",
  "store_order_refund_requests",
  "store_order_invoices",
  "store_customers",
  "store_wishlist",
  "store_price_alerts",
  "remote_companion_devices",
  "remote_install_jobs",
  "performance_sessions",
  "launcher_local_entities",
  "community_artwork_votes",
  "controller_layout_votes",
] as const;

export const exportAdditionalUserScopedReads = [
  {
    column: "submitter_id",
    key: "community_artwork_items",
    table: "community_artwork_items",
  },
  {
    column: "reporter_user_id",
    key: "community_artwork_reports",
    table: "community_artwork_reports",
  },
  {
    column: "reviewer_user_id",
    key: "community_artwork_moderation_audit",
    table: "community_artwork_moderation_audit",
  },
  {
    column: "reporter_id",
    key: "controller_layout_reports",
    table: "controller_layout_reports",
  },
  {
    column: "reviewer_id",
    key: "controller_layout_moderation_audit",
    table: "controller_layout_moderation_audit",
  },
  {
    column: "created_by",
    key: "share_tokens",
    table: "share_tokens",
  },
  {
    column: "owner_id",
    key: "mobile_push_registrations",
    table: "mobile_push_registrations",
  },
  {
    column: "developer_id",
    key: "store_products",
    table: "store_products",
  },
] as const;
