import type { StoreGame } from "./types";

export const storeGames: StoreGame[] = [
  {
    id: "deep-signal",
    title: "Wasteland Drifter",
    description: "Racing / Arcade",
    price: 19.99,
    originalPrice: 29.99,
    discountPercent: 33,
    platform: ["windows", "linux"],
    developer: "Signal Works",
    genres: ["Racing", "Arcade"],
    releaseDate: "2026-06-18",
    tagLine: "Racing / Arcade",
  },
  {
    id: "redline-tactics",
    title: "System Crash",
    description: "Puzzle / Hacking",
    price: 9.99,
    originalPrice: 14.99,
    discountPercent: 33,
    isFree: false,
    platform: ["windows"],
    developer: "Redline Lab",
    genres: ["Puzzle", "Hacking"],
    releaseDate: "2026-04-12",
    tagLine: "Puzzle / Hacking",
  },
  {
    id: "haven-forge",
    title: "Blood Tide",
    description: "Action / RPG",
    price: 29.99,
    platform: ["windows", "linux", "macos"],
    developer: "Haven Forge",
    genres: ["Action", "RPG"],
    releaseDate: "2026-08-03",
    tagLine: "Action / RPG",
  },
];
