[package]
name = "open-game-launcher"
version = "0.1.0"
description = "A cross-platform desktop game launcher MVP."
authors = ["Open Game Launcher"]
license = "AGPL-3.0-only"
edition = "2021"
rust-version = "1.82"

[lib]
name = "open_game_launcher_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dirs = "6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1.4"
sha2 = "0.10"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-deep-link = "2"
reqwest = { version = "0.13", features = ["blocking", "json", "stream", "form", "query"] }
rusqlite = { version = "0.40", features = ["bundled"] }
tungstenite = "0.24"
tokio = { version = "1", features = ["full"] }
sysinfo = { version = "0.39", features = ["serde"] }
futures-util = "0.3"
notify = "6"
zip = "8.6.0"
ureq = { version = "3.2.1", features = ["json"] }
keyring = "3"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.10"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
nvml-wrapper = "0.12"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
gilrs = "0.11"


[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.55"
windows-sys = { version = "0.61", features = ["Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse"] }

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
